#!/usr/bin/env python3
"""
parse_dbc.py — Parses a DBC file and generates Rust source with message/signal definitions.

Uses the same regex patterns as opendbc's dbc.py parser but without the numpy/car dependency chain.
Run: python3 scripts/parse_dbc.py dbc/toyota_tss2_adas.dbc > src/dbc_generated.rs
"""

import re
import sys
import os
from dataclasses import dataclass

# Same regex patterns used by opendbc/can/dbc.py
BO_RE = re.compile(r"^BO_ (\w+) (\w+) *: (\w+) (\w+)")
SG_RE = re.compile(
    r"^SG_ (\w+) : (\d+)\|(\d+)@(\d)([+-]) "
    r"\(([0-9.+\-eE]+),([0-9.+\-eE]+)\) "
    r"\[([0-9.+\-eE]+)\|([0-9.+\-eE]+)\] "
    r'"(.*?)" (.*)'
)
BU_RE = re.compile(r"^BU_:\s*(.*)")


@dataclass
class Signal:
    name: str
    start_bit: int
    size: int
    is_little_endian: bool
    is_signed: bool
    factor: float
    offset: float
    min_val: float
    max_val: float
    unit: str
    receivers: str
    # Computed fields
    msb: int = 0
    lsb: int = 0
    is_checksum: bool = False
    is_counter: bool = False


@dataclass
class Message:
    msg_id: int
    name: str
    dlc: int
    sender: str
    signals: list


def parse_dbc(path: str):
    """Parse a DBC file, returning (nodes, messages)."""
    be_bits = [j + i * 8 for i in range(64) for j in range(7, -1, -1)]

    nodes = []
    messages = []
    current_msg = None

    with open(path) as f:
        for line in f:
            line = line.strip()

            # Node definitions
            m = BU_RE.match(line)
            if m:
                node_str = m.group(1).strip()
                if node_str:
                    nodes = [n.strip() for n in node_str.split() if n.strip()]
                continue

            # Message definition
            m = BO_RE.match(line)
            if m:
                msg_id = int(m.group(1), 0)
                msg_name = m.group(2)
                dlc = int(m.group(3), 0)
                sender = m.group(4)
                current_msg = Message(msg_id, msg_name, dlc, sender, [])
                messages.append(current_msg)
                continue

            # Signal definition
            m = SG_RE.match(line)
            if m and current_msg is not None:
                sig_name = m.group(1)
                start_bit = int(m.group(2))
                size = int(m.group(3))
                is_little_endian = m.group(4) == "1"
                is_signed = m.group(5) == "-"
                factor = float(m.group(6))
                offset = float(m.group(7))
                min_val = float(m.group(8))
                max_val = float(m.group(9))
                unit = m.group(10)
                receivers = m.group(11).strip()

                # Compute MSB/LSB (same logic as opendbc)
                if is_little_endian:
                    lsb = start_bit
                    msb = start_bit + size - 1
                else:
                    idx = be_bits.index(start_bit)
                    lsb = be_bits[idx + size - 1]
                    msb = start_bit

                sig = Signal(
                    name=sig_name,
                    start_bit=start_bit,
                    size=size,
                    is_little_endian=is_little_endian,
                    is_signed=is_signed,
                    factor=factor,
                    offset=offset,
                    min_val=min_val,
                    max_val=max_val,
                    unit=unit,
                    receivers=receivers,
                    msb=msb,
                    lsb=lsb,
                    is_checksum=(sig_name == "CHECKSUM"),
                    is_counter=(sig_name == "COUNTER"),
                )
                current_msg.signals.append(sig)

    return nodes, messages


def rust_ident(name: str) -> str:
    """Convert a DBC name to a valid Rust identifier."""
    return name.upper().replace(" ", "_")


def generate_rust(nodes, messages, dbc_name):
    """Generate Rust source code with compiled-in DBC definitions."""
    lines = []
    lines.append("//! Auto-generated from DBC file. DO NOT EDIT.")
    lines.append(f"//! Source: {dbc_name}")
    lines.append(f"//! Messages: {len(messages)}")
    lines.append("//!")
    lines.append("//! Generated by scripts/parse_dbc.py")
    lines.append("")
    lines.append("/// A signal definition within a CAN message.")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub struct DbcSignalDef {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub start_bit: u16,")
    lines.append("    pub size: u8,")
    lines.append("    pub is_little_endian: bool,")
    lines.append("    pub is_signed: bool,")
    lines.append("    pub factor: f64,")
    lines.append("    pub offset: f64,")
    lines.append("    pub min_val: f64,")
    lines.append("    pub max_val: f64,")
    lines.append("    pub unit: &'static str,")
    lines.append("    pub msb: u16,")
    lines.append("    pub lsb: u16,")
    lines.append("    pub is_checksum: bool,")
    lines.append("    pub is_counter: bool,")
    lines.append("}")
    lines.append("")
    lines.append("/// A CAN message definition from the DBC file.")
    lines.append("#[derive(Debug, Clone)]")
    lines.append("pub struct DbcMessageDef {")
    lines.append("    pub msg_id: u32,")
    lines.append("    pub name: &'static str,")
    lines.append("    pub dlc: u8,")
    lines.append("    pub sender: &'static str,")
    lines.append("    pub signals: &'static [DbcSignalDef],")
    lines.append("}")
    lines.append("")

    # Generate signal arrays for each message
    for msg in messages:
        sig_array_name = f"SIGS_{rust_ident(msg.name)}"
        lines.append(f"static {sig_array_name}: &[DbcSignalDef] = &[")
        for sig in msg.signals:
            lines.append(f"    DbcSignalDef {{")
            lines.append(f'        name: "{sig.name}",')
            lines.append(f"        start_bit: {sig.start_bit},")
            lines.append(f"        size: {sig.size},")
            lines.append(f"        is_little_endian: {str(sig.is_little_endian).lower()},")
            lines.append(f"        is_signed: {str(sig.is_signed).lower()},")
            lines.append(f"        factor: {sig.factor},")
            lines.append(f"        offset: {sig.offset},")
            lines.append(f"        min_val: {sig.min_val},")
            lines.append(f"        max_val: {sig.max_val},")
            lines.append(f'        unit: "{sig.unit}",')
            lines.append(f"        msb: {sig.msb},")
            lines.append(f"        lsb: {sig.lsb},")
            lines.append(f"        is_checksum: {str(sig.is_checksum).lower()},")
            lines.append(f"        is_counter: {str(sig.is_counter).lower()},")
            lines.append(f"    }},")
        lines.append("];")
        lines.append("")

    # Generate the master message table
    lines.append(f"/// All {len(messages)} messages from {dbc_name}.")
    lines.append(f"pub static DBC_MESSAGES: &[DbcMessageDef] = &[")
    for msg in messages:
        sig_array_name = f"SIGS_{rust_ident(msg.name)}"
        lines.append(f"    DbcMessageDef {{")
        lines.append(f"        msg_id: 0x{msg.msg_id:03X},")
        lines.append(f'        name: "{msg.name}",')
        lines.append(f"        dlc: {msg.dlc},")
        lines.append(f'        sender: "{msg.sender}",')
        lines.append(f"        signals: {sig_array_name},")
        lines.append(f"    }},")
    lines.append("];")
    lines.append("")

    # Generate constants for message IDs
    lines.append("// Message ID constants")
    for msg in messages:
        const_name = f"MSG_ID_{rust_ident(msg.name)}"
        lines.append(f"pub const {const_name}: u32 = 0x{msg.msg_id:03X};")
    lines.append("")

    # Generate total count
    lines.append(f"pub const DBC_MESSAGE_COUNT: usize = {len(messages)};")
    lines.append(f'pub const DBC_NAME: &str = "{dbc_name}";')
    lines.append("")

    # Generate a node list
    if nodes:
        lines.append(f"pub static DBC_NODES: &[&str] = &[")
        for node in nodes:
            lines.append(f'    "{node}",')
        lines.append("];")
    else:
        lines.append("pub static DBC_NODES: &[&str] = &[];")
    lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <dbc_file>", file=sys.stderr)
        sys.exit(1)

    dbc_path = sys.argv[1]
    dbc_name = os.path.basename(dbc_path).replace(".dbc", "")

    nodes, messages = parse_dbc(dbc_path)

    print(f"Parsed {dbc_name}: {len(messages)} messages, {len(nodes)} nodes",
          file=sys.stderr)
    for msg in messages:
        print(f"  0x{msg.msg_id:03X} {msg.name}: {msg.dlc}B, "
              f"{len(msg.signals)} signals ({msg.sender})",
              file=sys.stderr)

    rust_code = generate_rust(nodes, messages, dbc_name)
    print(rust_code)


if __name__ == "__main__":
    main()
