import "../justfile"

# Cross-compile armv7 binaries and deploy them to copper7.
cross-armv7-deploy:
	#!/usr/bin/env bash
	set -euo pipefail
	cd ..
	cross build --target armv7-unknown-linux-gnueabihf --release
	find target/armv7-unknown-linux-gnueabihf/release -maxdepth 1 -type f -executable -exec scp -r {} gbin@copper7:copper/ \;
	scp copper_derive_test/copperconfig.ron gbin@copper7:copper

# Cross-compile riscv64 binaries and deploy them to copperv.
cross-riscv64-deploy:
	#!/usr/bin/env bash
	set -euo pipefail
	cd ..
	cross build --target riscv64gc-unknown-linux-gnu --release
	find target/riscv64gc-unknown-linux-gnu/release -maxdepth 1 -type f -executable -exec scp -r {} gbin@copperv:copper/ \;
	scp copper_derive_test/copperconfig.ron gbin@copperv:copper
