import "../../justfile"
ping:
  #!/usr/bin/env bash
  set -euo pipefail
  cargo run -p cu-zenoh-bridge-demo --bin zenoh-ping

pong:
  #!/usr/bin/env bash
  set -euo pipefail
  cargo run -p cu-zenoh-bridge-demo --bin zenoh-pong
