#!/bin/bash
set -euo pipefail

# A small shortcut to be able to extract your structured log.
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
RUST_BACKTRACE=1 cargo run --features=logreader -p {{project-name|kebab_case}} --bin {{project-name|kebab_case}}-logreader logs/{{project-name|kebab_case}}.copper extract-text-log target/debug/cu29_log_index
