repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=4096"]
      # - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-symlinks
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: ["--branch=master"]

  - repo: local
    hooks:
      - id: typos
        name: check typos (with typos-cli)
        entry: typos -c .config/_typos.toml
        language: system
        pass_filenames: false
      - id: check-rust
        name: check rust format
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: check-ron
        name: check RON (with fmtron)
        entry: bash support/ci/check_ron_format.sh
        language: system
        pass_filenames: false
      - id: check-toml
        name: check toml (with taplo)
        entry: bash -c "git ls-files -z '*.toml' | xargs -0 taplo format --check"
        language: system
        pass_filenames: false
