import "../../justfile"

cl:
	#!/usr/bin/env bash
	set -euo pipefail
	RUST_BACKTRACE=1 cargo run --bin logreader /tmp/caterpillar.copper extract-copperlist

dag:
	#!/usr/bin/env bash
	set -euo pipefail
	../../target/release/copper-rendercfg copperconfig.ron --open

logreader:
	#!/usr/bin/env bash
	set -euo pipefail
	RUST_BACKTRACE=1 cargo run --bin cu-caterpillar-logreader logs/caterpillar.copper extract-log ../../target/debug/copper_log_index

resim:
	#!/usr/bin/env bash
	set -euo pipefail
	RUST_BACKTRACE=1 cargo run --bin cu-caterpillar-resim logs/caterpillar.copper
