(function() {var implementors = {
"gpio_cdev":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"gpio_cdev/struct.LineEventHandle.html\" title=\"struct gpio_cdev::LineEventHandle\">LineEventHandle</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"gpio_cdev/struct.LineHandle.html\" title=\"struct gpio_cdev::LineHandle\">LineHandle</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"gpio_cdev/struct.MultiLineHandle.html\" title=\"struct gpio_cdev::MultiLineHandle\">MultiLineHandle</a>"]],
"i2cdev":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"i2cdev/linux/struct.LinuxI2CBus.html\" title=\"struct i2cdev::linux::LinuxI2CBus\">LinuxI2CBus</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"i2cdev/linux/struct.LinuxI2CDevice.html\" title=\"struct i2cdev::linux::LinuxI2CDevice\">LinuxI2CDevice</a>"]],
"libudev":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"libudev/struct.MonitorSocket.html\" title=\"struct libudev::MonitorSocket\">MonitorSocket</a>"]],
"rustix":[],
"same_file":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"same_file/struct.Handle.html\" title=\"struct same_file::Handle\">Handle</a>"]],
"serialport":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"serialport/struct.TTYPort.html\" title=\"struct serialport::TTYPort\">TTYPort</a>"]],
"spidev":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"spidev/struct.Spidev.html\" title=\"struct spidev::Spidev\">Spidev</a>"]],
"tempfile":[["impl&lt;F: <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.80.0/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"tempfile/struct.NamedTempFile.html\" title=\"struct tempfile::NamedTempFile\">NamedTempFile</a>&lt;F&gt;"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()