[package]
name = "custom-planner"
description = "Example out-of-tree execution planner for cu-custom-planner."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

publish = false

[dependencies]
cu29 = { workspace = true }
