import "../../justfile"

# A quick test to see if the sim can pick up your RC.
rc:
  #!/usr/bin/env bash
  cargo run -p cu-basic-fc --no-default-features --features sim --bin rc-tester

# Build firmware-only target using the firmware-specific Cargo config
fw:
  #!/usr/bin/env bash
  set -euo pipefail
  cargo run --release --config .cargo/config-firmware.toml --no-default-features --features firmware -p cu-basic-fc --bin quad

# Build firmware-only target using the firmware-specific Cargo config
fwd:
  #!/usr/bin/env bash
  set -euo pipefail
  cargo run --config .cargo/config-firmware.toml --no-default-features --features firmware -p cu-basic-fc --bin quad

# Attach to the already-flashed target without rebuilding or flashing.
attach:
  #!/usr/bin/env bash
  set -euo pipefail
  probe-rs attach --chip STM32H743VITx --protocol swd ../../target/thumbv7em-none-eabihf/release/quad
