import "../../justfile"

dev-opt:
  #!/usr/bin/env bash
  cargo run -p cu-elrs-bdshot-demo --profile dev-opt

attach:
  #!/usr/bin/env bash
  set -euo pipefail
  probe-rs attach ../../target/thumbv8m.main-none-eabihf/debug/cu-elrs-bdshot-demo

attach-dev-opt:
  #!/usr/bin/env bash
  set -euo pipefail
  probe-rs attach ../../target/thumbv8m.main-none-eabihf/dev-opt/cu-elrs-bdshot-demo

dag:
  #!/usr/bin/env bash
  pushd {{ROOT}}
  cargo run -p cu29-runtime --bin cu29-rendercfg -- --open examples/cu_elrs_bdshot_demo/copperconfig.ron 
  popd
