[package]
name = "cargo-cunew"
description = "Bootstrap Copper projects from bundled templates."
version = "1.2.4"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/cargo-cunew"
readme = "README.md"
include = ["README.md", "src/**", "templates/**"]

[dependencies]
anyhow = { workspace = true, features = ["std"] }
heck = "~0.5"
liquid = "~0.26"
liquid-core = "~0.26"
liquid-derive = "~0.26"
semver = "~1.0"
clap = { workspace = true }
include_dir = "0.7.4"
pathdiff = "0.2.3"
ureq = { version = "~3.4", default-features = false, features = [
  "json",
  "rustls",
] }
serde = { workspace = true, features = ["std"] }
tempfile = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
