[package]
name = "cu-serial-bridge"
description = "Nonblocking raw byte bridge for Copper"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.copper]
kind = "bridge"
domains = ["communication/serial"]
environments = ["host", "embedded"]

[dependencies]
embedded-io = { version = "0.7.1", default-features = false }
cu29 = { path = "../../../core/cu29", version = "1.2.0", default-features = false }
cu-serial = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }

[features]
default = ["std"]
std = ["cu29/std", "cu-serial/std"]

[build-dependencies]
cu29-build = { workspace = true }
