[package]
name = "cu29-value"
description = "This is a fork of Value with custom types added for Copper like the time and units."

version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true

authors = ["arcnmx", "gbin"]

readme = "README.md"
keywords = ["serde"]
license = "MIT"

documentation = "https://docs.rs/cu29-value"

[dependencies]
cu29-value-types = { workspace = true, features = ["serde"] }
bevy_reflect = { workspace = true, optional = true }
cu29-units = { workspace = true, optional = true }
cu29-clock = { workspace = true }

bincode = { workspace = true }
serde = { workspace = true }
ordered-float = { version = "5.1", default-features = false }
pyo3 = { workspace = true, optional = true }

[dev-dependencies]
trybuild = "1.0"
serde_derive = { workspace = true }

[features]
self-describing-logs = [
  "std",
  "bincode/self-describing",
  "dep:bevy_reflect",
  "cu29-clock/reflect",
  "dep:cu29-units",
  "cu29-units/reflect",
]
default = ["std"]
std = ["ordered-float/std", "cu29-clock/std", "cu29-units?/std"]
python = ["std", "dep:pyo3"]
