//! Build-host packaging of instantiated native payload descriptions.

use cu29_traits::CuError;
use cu29_traits::CuResult;
use cu29_value::catalog::ValueDecodeCatalog;
use cu29_value::catalog::ValueDecodeCatalogHeader;
use std::fmt::Write;
use std::path::Path;

/// Write a compressed catalog as a Rust static byte array in Cargo's `OUT_DIR`.
///
/// `file_name` names the generated source and must be a single `.rs` filename.
/// Include it with `include!(concat!(env!("OUT_DIR"), "/catalog.rs"))` to obtain
/// `VALUE_DECODE_CATALOG: &[u8]`. Compression and description construction run
/// entirely on the host, including when Cargo builds an application for another target.
pub fn write_value_decode_catalog(file_name: &str, catalog: &ValueDecodeCatalog) -> CuResult<()> {
    if Path::new(file_name)
        .file_name()
        .and_then(|name| name.to_str())
        != Some(file_name)
        || !file_name.ends_with(".rs")
    {
        return Err("Catalog output must be a single .rs filename".into());
    }
    let out_dir = std::env::var_os("OUT_DIR").ok_or(CuError::from("Cargo must provide OUT_DIR"))?;
    let blob = catalog
        .to_blob()
        .map_err(|error| CuError::from(format!("Could not package ValueDecodeCatalog: {error}")))?;
    ValueDecodeCatalogHeader::read(&blob)
        .map_err(|error| CuError::new_with_cause("Invalid packaged ValueDecodeCatalog", error))?;
    let mut source =
        String::from("// Generated by cu29-build.\npub static VALUE_DECODE_CATALOG: &[u8] = &[\n");
    for chunk in blob.chunks(24) {
        source.push_str("    ");
        for byte in chunk {
            write!(source, "{byte},").map_err(|error| {
                CuError::new_with_cause("Could not format ValueDecodeCatalog source", error)
            })?;
        }
        source.push('\n');
    }
    source.push_str("];\n");
    let output = Path::new(&out_dir).join(file_name);
    // Do not force downstream recompilation when packaging reproduces the same blob.
    if std::fs::read_to_string(&output).ok().as_deref() != Some(&source) {
        std::fs::write(output, source).map_err(|error| {
            CuError::new_with_cause("Could not write ValueDecodeCatalog source", error)
        })?;
    }
    println!(
        "cargo::warning=ValueDecodeCatalog: {} embedded bytes (including header)",
        blob.len()
    );
    Ok(())
}
